# =============================================================================
# BUILD STAGE
# =============================================================================
FROM node:22.18.0-alpine3.22 AS build

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_FRONTEND_URL
ARG NEXT_IMAGE_REMOTE_SOURCES
# Keep local Docker builds disabled unless prod release tooling passes true.
ARG NEXT_PUBLIC_STRIPE_ENABLED=false
ARG NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=false
ARG NEXT_PUBLIC_GITHUB_AUTH_ENABLED=false
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_AI_ENABLED=false
ARG NEXT_PUBLIC_SUPPORT_CHAT_ENABLED=false
ARG NEXT_PUBLIC_SUPPORT_CHAT_WS_URL
ARG NEXT_PUBLIC_EMAIL_CONFIRMATION_ENABLED=false
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG NEXT_PUBLIC_TURNSTILE_SUPPORT_CHAT_ENABLED=false
ARG NEXT_PUBLIC_TURNSTILE_CHECKOUT_ENABLED=false
ARG NEXT_PUBLIC_TURNSTILE_REVIEWS_ENABLED=false
ARG NEXT_PUBLIC_TURNSTILE_AVATAR_ENABLED=false
ARG NEXT_PUBLIC_SENTRY_ENABLED=false
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_SENTRY_ENVIRONMENT=production
ARG NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE=0.1
ARG NEXT_PUBLIC_SENTRY_REPLAYS_SESSION_SAMPLE_RATE=0
ARG NEXT_PUBLIC_SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE=1
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG SENTRY_RELEASE
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL
ENV NEXT_IMAGE_REMOTE_SOURCES=$NEXT_IMAGE_REMOTE_SOURCES
ENV NEXT_PUBLIC_STRIPE_ENABLED=$NEXT_PUBLIC_STRIPE_ENABLED
ENV NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=$NEXT_PUBLIC_GOOGLE_AUTH_ENABLED
ENV NEXT_PUBLIC_GITHUB_AUTH_ENABLED=$NEXT_PUBLIC_GITHUB_AUTH_ENABLED
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ENV NEXT_PUBLIC_AI_ENABLED=$NEXT_PUBLIC_AI_ENABLED
ENV NEXT_PUBLIC_SUPPORT_CHAT_ENABLED=$NEXT_PUBLIC_SUPPORT_CHAT_ENABLED
ENV NEXT_PUBLIC_SUPPORT_CHAT_WS_URL=$NEXT_PUBLIC_SUPPORT_CHAT_WS_URL
ENV NEXT_PUBLIC_EMAIL_CONFIRMATION_ENABLED=$NEXT_PUBLIC_EMAIL_CONFIRMATION_ENABLED
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV NEXT_PUBLIC_TURNSTILE_SUPPORT_CHAT_ENABLED=$NEXT_PUBLIC_TURNSTILE_SUPPORT_CHAT_ENABLED
ENV NEXT_PUBLIC_TURNSTILE_CHECKOUT_ENABLED=$NEXT_PUBLIC_TURNSTILE_CHECKOUT_ENABLED
ENV NEXT_PUBLIC_TURNSTILE_REVIEWS_ENABLED=$NEXT_PUBLIC_TURNSTILE_REVIEWS_ENABLED
ENV NEXT_PUBLIC_TURNSTILE_AVATAR_ENABLED=$NEXT_PUBLIC_TURNSTILE_AVATAR_ENABLED
ENV NEXT_PUBLIC_SENTRY_ENABLED=$NEXT_PUBLIC_SENTRY_ENABLED
ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV NEXT_PUBLIC_SENTRY_ENVIRONMENT=$NEXT_PUBLIC_SENTRY_ENVIRONMENT
ENV NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE=$NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE
ENV NEXT_PUBLIC_SENTRY_REPLAYS_SESSION_SAMPLE_RATE=$NEXT_PUBLIC_SENTRY_REPLAYS_SESSION_SAMPLE_RATE
ENV NEXT_PUBLIC_SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE=$NEXT_PUBLIC_SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE
ENV SENTRY_ORG=$SENTRY_ORG
ENV SENTRY_PROJECT=$SENTRY_PROJECT
ENV SENTRY_RELEASE=$SENTRY_RELEASE

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY src/ ./src/
COPY public/ ./public/
COPY next.config.js tsconfig.json postcss.config.js next-env.d.ts ./
RUN npm run build

# =============================================================================
# RUNTIME STAGE
# =============================================================================
FROM node:22.18.0-alpine3.22

LABEL maintainer="Iced-Latte Team" \
      description="Iced-Latte Frontend Application"

WORKDIR /app

ENV NODE_ENV=production \
    HOSTNAME=0.0.0.0

COPY --from=build --chown=node:node /app/public ./public
COPY --from=build --chown=node:node /app/.next/static ./.next/static
COPY --from=build --chown=node:node /app/.next/standalone ./

RUN mkdir -p /app/.next/cache \
 && chown -R node:node /app

USER node

ENTRYPOINT ["node", "server.js"]
