version: "3.5"

networks:
  iced-latte-network:
    name: iced-latte-network
    attachable: true

services:
  iced-latte-frontend:
    image: 'zufarexplainedit/iced-latte-frontend:${DOCKER_IMAGE_TAG}'
    container_name: iced-latte-frontend
    env_file:
      - .frontend_env
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    networks:
      - iced-latte-network
