const comments = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    rating: 4,
    date: '16.02.2024',
    time: '10:30',
    text: 'Just the other day, I had the pleasure of experiencing the epitome of coffee perfection at [Coffee Shop Name]. Their [coffee name] was an absolute delight to the senses, delivering a symphony of flavors that danced on my tongue and awakened my soul. The aroma that wafted from the freshly brewed cup was intoxicating, a blend of dark chocolate, caramel, and subtle hints of berries that promised an unforgettable experience.',
    likes: 10,
    dislikes: 2,
    isCurrentUserComment: true,
  },
  {
    id: '2',
    firstName: 'Alice',
    lastName: 'Smith',
    rating: 5,
    date: '15.02.2024',
    time: '14:45',
    text: 'Excellent service and fast delivery. Highly recommend!',
    likes: 15,
    dislikes: 0,
    isCurrentUserComment: false,
  },
  {
    id: '3',
    firstName: 'Alicered',
    lastName: 'Smith',
    rating: 3,
    date: '15.02.2024',
    time: '14:45',
    text: 'Excellent service and fast delivery. Highly recommend!',
    likes: 15,
    dislikes: 0,
    isCurrentUserComment: false,
  },
  {
    id: '4',
    firstName: 'Alice',
    lastName: 'Smith',
    rating: 5,
    date: '15.02.2024',
    time: '14:45',
    text: 'Excellent service and fast delivery. Highly recommend!',
    likes: 15,
    dislikes: 0,
    isCurrentUserComment: false,
  },
  {
    id: '5',
    firstName: 'Alice',
    lastName: 'Smith',
    rating: 4,
    date: '15.02.2024',
    time: '14:45',
    text: 'Excellent service and fast delivery. Highly recommend!',
    likes: 7,
    dislikes: 3,
    isCurrentUserComment: false,
  },
  {
    id: '6',
    firstName: 'Alice',
    lastName: 'Smith',
    rating: 3,
    date: '15.02.2024',
    time: '14:45',
    text: 'Excellent service and fast delivery. Highly recommend!',
    likes: 17,
    dislikes: 4,
    isCurrentUserComment: false,
  },
  {
    id: '7',
    firstName: 'Alice',
    lastName: 'Smith',
    rating: 2,
    date: '15.02.2024',
    time: '14:45',
    text: 'Excellent service and fast delivery. Highly recommend!',
    likes: 10,
    dislikes: 0,
    isCurrentUserComment: false,
  },
  {
    id: '8',
    firstName: 'Alice',
    lastName: 'Smith',
    rating: 1,
    date: '15.02.2024',
    time: '14:45',
    text: 'Excellent service and fast delivery. Highly recommend!',
    likes: 11,
    dislikes: 0,
    isCurrentUserComment: false,
  },
]

export default comments
