name: Build and Deploy

on:
  pull_request:
    types: [ closed ]
    branches:
      - master


jobs:
  build-and-push-docker-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from the repository
        uses: actions/checkout@v4

      - name: Set DOCKER_IMAGE_TAG
        run: echo "DOCKER_IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        run: |
          docker build -t dzmitrybond/iced_front .
          docker tag dzmitrybond/iced_front:latest dzmitrybond/iced_front:test1
          docker tag dzmitrybond/iced_front:latest dzmitrybond/iced_front:test2
      - name: Push Docker image to DockerHub
        run: |
          docker push dzmitrybond/iced_front:test1
          docker push dzmitrybond/iced_front:test2

  deploy-app-to-server:
    name: Deploy application to remote server via ssh
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Set DOCKER_IMAGE_TAG
        run: echo "DOCKER_IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Deploy image via SSH
        uses: appleboy/ssh-action@v1.0.0
        env:
          DOCKER_IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIV_KEY }}
          envs: DOCKER_IMAGE_TAG
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
            docker stop iced_front_test1 | true
            docker rm iced_front_test1 | true
            docker rmi dzmitrybond/iced_front:test1 | true
            docker pull dzmitrybond/iced_front:test1 |true
            docker stop iced_front_test2 | true
            docker rm iced_front_test2 | true
            docker rmi dzmitrybond/iced_front:test2 | true
            docker pull dzmitrybond/iced_front:test2 |true
            docker run -d --name 'iced_front_test1' --network=iced-latte-network dzmitrybond/iced_front:test1
            docker run -d --name 'iced_front_test2' --network=iced-latte-network dzmitrybond/iced_front:test2
